version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Europe/Paris"
    target-branch: development

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Europe/Paris"
    target-branch: development

  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Europe/Paris"
    target-branch: development
