targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: explorer_ui|lib/graphql/schema.graphql
          output_dir: api

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: explorer_ui|lib/graphql/schema.graphql
          output_dir: api