name: explorer_ui
description: Royllo explorer user interface

# The following line prevents the package from being accidentally published to
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Go_router to manage navigation.
  go_router: ^6.0.1

  # Riverpod dependencies (used for api calls).
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1

  # GraphQL integration
  ferry: ^0.13.0
  gql_http_link: ^0.4.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # UI utils
  number_paginator: ^0.2.3

# dev_dependencies are dependencies that are not available for code in the resulting application,
# but only for tests, examples, tools, or to add executable tools like for code generation to your project.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The build_runner package provides a concrete way of generating files using Dart code, outside of tools like pub.
  # Unlike pub serve/build, files are always generated directly on disk, and rebuilds are incremental.
  build_runner: ^2.3.3

  # Riverpod dependencies.
  riverpod_generator: ^1.1.1

  # GraphQL dependencies.
  ferry_generator: ^0.7.0

  # Mockito
  mockito: ^5.3.2

  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # This section add assets to your application.
  assets:
    - assets/images/logo_homepage.png
    - assets/images/logo_large_with_text.png
    - assets/images/logo_large_without_text.png
