name: Push on develop - Build, test, package, create docker image & push it to docker hub

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: Retrieve the sources
        uses: actions/checkout@v3

      # ================================================================================================================
      - name: JDK 17 Setup
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '17'

      # ================================================================================================================
      - name: Get release number
        id: release
        run: echo "::set-output name=version::$(mvn help:evaluate -D expression=project.version -q -D forceStdout)"

      # ================================================================================================================
      - name: Run core & issues tests
        run: mvn clean test

      # ================================================================================================================
      - name: Run integration tests
        run: mvn clean test -P integration

      # ================================================================================================================
      - name: Docker Hub login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.EXPLORER_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.EXPLORER_DOCKER_HUB_PASSWORD }}

      # ================================================================================================================
      - name: Build docker image
        run: mvn spring-boot:build-image -f backend/pom.xml

      # ================================================================================================================
      - name: Push the docker images to Docker hub
        run: |
          docker tag royllo/explorer:latest royllo/explorer:${{ steps.release.outputs.version }}
          docker push royllo/explorer:latest
          docker push royllo/explorer:${{ steps.release.outputs.version }}