name: Push on develop - Build, test, package, create docker image & push it to docker hub

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: Retrieve the sources
        uses: actions/checkout@v3

      # ================================================================================================================
      - name: JDK Setup
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'temurin'
          java-version: '17'

      # ================================================================================================================
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'

      # ================================================================================================================
      - name: Get release number
        id: release
        run: echo "::set-output name=version::$(mvn help:evaluate -D expression=project.version -q -D forceStdout)"

      # ================================================================================================================
      - name: Run backend tests
        run: |
          mvn clean test
          mvn clean test -P integration
          mvn clean install -Dmaven.test.skip

      # ================================================================================================================
      - name: Run frontend tests & build artifacts
        working-directory: frontend/explorer_ui
        run: |
          flutter build web

      # ================================================================================================================
      - name: Build and tag docker images
        run: |
          mvn spring-boot:build-image -Dmaven.test.skip -f backend/explorer-batch/pom.xml
          mvn spring-boot:build-image -Dmaven.test.skip -f backend/explorer-api/pom.xml
          docker build -t royllo/explorer-www:latest -f frontend/explorer_ui/Dockerfile frontend/explorer_ui/
          docker tag royllo/explorer-batch:latest royllo/explorer-batch:${{ steps.release.outputs.version }}
          docker tag royllo/explorer-api:latest royllo/explorer-api:${{ steps.release.outputs.version }}
          docker tag royllo/explorer-www:latest royllo/explorer-www:${{ steps.release.outputs.version }}

      # ================================================================================================================
      - name: Run the docker-compose with our images
        run: |
          docker-compose up >> docker.logs 2>&1 &
          sleep 60        

      # ================================================================================================================
      - name: Testing docker images with a curl call to the userByUsername method
        id: userByUsername
        run: |
          userByUsernameResult=$(curl  -H "Content-Type: application/json" \
                -d '{ "query": "{ userByUsername(username: \"anonymous\") { id, username }}" }' \
                http://localhost:9090/graphql | jq '.data.userByUsername.id')
          echo "userByUsername call result is ${userByUsernameResult}"
          echo "userByUsernameResult=${userByUsernameResult}" >> $GITHUB_OUTPUT

      - name: Check if userByUsername returns the correct value
        if: ${{ steps.userByUsername.outputs.userByUsernameResult != '"0"' }}
        run: |
          echo "Error - userByUsername id result is ${{ steps.userByUsername.outputs.userByUsernameResult }}"
          cat docker.logs
          exit 1

      # ================================================================================================================
      - name: Docker Hub login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.EXPLORER_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.EXPLORER_DOCKER_HUB_PASSWORD }}

      # ================================================================================================================
      - name: Push the docker images to Docker hub
        run: |
          docker push royllo/explorer-batch:latest
          docker push royllo/explorer-batch:${{ steps.release.outputs.version }}
          docker push royllo/explorer-api:latest
          docker push royllo/explorer-api:${{ steps.release.outputs.version }}
          docker push royllo/explorer-www:latest
          docker push royllo/explorer-www:${{ steps.release.outputs.version }}